config/routes.rb
Rails.application.routes.draw do
    
  get '/index' => 'welcome#index'
  get '/welcome' => 'welcome#index'
  root :to => 'welcome#index'
  
  get '/signup' => 'signup#new'
  resources :users
  
  post '/login' => 'login#index'
  
  get '/logout' => 'login#delete'
  
  get '/posts/new' => 'posts#new'
  get '/posts' => 'posts#index'
  post '/posts/create' => 'posts#create'
  
  get '/info' => 'info#index'
  get '/about' => 'about#index'
  get '/contacts' => 'contacts#index'
  get '/callback' => 'callback#index'
  

end

app/models/info.rb
class Info < ActiveRecord::Base
    has_one :user
    
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    belongs_to :info
    
    validates :name, presence: true
    
    def editor?
      self.role == "admin"
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
    def index
        
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def index
    p = login_user_params
    pass = User.find_by(email: p[:user_login])
    
    if pass && pass.password_digest == p[:user_password]
        session[:user_id] = pass.id
        redirect_to '/'
    else
        redirect_to '/signup'
    end
  end
  
  def delete
    session[:user_id] = nil
    redirect_to '/'
  end
  
  private
    def login_user_params
      params.require(:user).permit(:user_login, :user_password)
    end
    
    def edit_phone(phone)
      result = ""
      ar_num = Array("0".."9")
      phone.chars.each do |i|
    	if ar_num.include? i
    		result += i
    	end
      end
      result   
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
      
    def index
      @posts = Post.all
    end
    
    def new
      @user = current_user
      if !(@user && @user.editor?)
        redirect_to ''
      end
      @post = Post.new
    end
    
    def create
      pass = post_params
      pass[:text].gsub!(/\n/, '<br />')
      pass[:text] = "" + pass[:text]
      if(@post = Post.create(pass))
        redirect_to '/posts'
      elsif
        redirect_to '/posts/new'
      end
    end
    
    private
      def post_params
        params.require(:post).permit(:topic, :text, :image)
      end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  
  def new
      @user = User.new
      @user.info = Info.new
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new        
    end
    
    def create
      p = user_params
      p[:name] = p[:email]
      @user = User.create(p)
      @user.info = Info.create(user_info_params)
      if @user.save
        session[:user_id] = @user.id
        session[:error] = nil
        redirect_to '/'
      else
        session[:error] =  @user.errors.full_messages[0]
        redirect_to '/signup'
      end
    end
    
    def show
      id = params[:id]
      if(id == "all") 
        @user = User.all
        return
      end
      @user = User.find(id)
    end
    
    private
        def user_params
          params.require(:user).permit(:email, :password_digest, :password_confirmation)
        end
        def user_info_params
          params.require(:user).require(:info).permit(
            :phone, :first_name, :last_name, :school, :group, :class_number)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
      
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   
   def current_user
    if(session[:user_id].nil?) 
        return false 
    end
    user = User.find(session[:user_id])
    if(user == nil)
      return false
    else
      return user
    end
   end
  
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loggek</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="../../js/main.js"></script>   
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wraper">

<div id="header">

<% if @current_path == "welcome#index" %>
   <div id="enter">
       <div class="enter-test">
         <div class="enter-in">
         <% if session[:user_id].nil? %>
           <%= form_for("user", url: login_path) do |f| %>
         
               <p class="text">Авторизация</p>
               
               <p><%= f.email_field :user_login, :placeholder => "Email" %></p>
    		   <p><%= f.password_field :user_password, :placeholder => "Password" %></p>
    		
    		<div style="width:100%; text-align:center;">
    		<%= f.submit "Sign up" %>
    		<p><small><a href="/signup">Или создать аккаунт?</a></small></p>
            </div>
            
            <% end %>
            <% elsif (pupil = current_user) %>
                <p class="text">Ученик</p>
                <p><%=pupil.info.first_name + " " + pupil.info.last_name%></p>
                <p>Телефон <%=pupil.info.phone%></p>
                <p>Почта <%=pupil.email%></p>
                <p>Школа № <%=pupil.info.school + " " +
                             pupil.info.class_number  + " \"" +
                             pupil.info.group.to_i.chr + "\""
                          %></p>
                <p><a href="/logout">Выйти</a></p>
            <% end %>
       </div>
        
   </div>
   </div>
<% end %>

   <div id="right">
       <div><a href="/callback">Обратная связь</a></div>
   </div>     
</div>

<%= yield %>
    
</div>

<div id="footer">
    <ul id="footer_menu">
        <li><a class="open-topic" href="/info">Набережная А.П.</a></li>
        <li><a class="open-topic" href="/contacts">Контакты</a></li>
        <li><a class="open-topic" href="/about">О нас</a></li>
    </ul>
    <p><a href="http://sch1852.mskobr.ru">Школа №1852</a></p>

</div>

</body>
</html>